services:
  - postgresql

addons:
  postgresql: '11.2'

env:
  global:
    - PGPORT=5433

dist: xenial

language: node_js

node_js:
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

# end to end testing template
e2e_tests: &e2e_tests
  stage: 'End to End tests CE'
  script:
    - LEEMONS_DISABLE_EE=true yarn run -s test:generate-app -- $DB_STRING
    - LEEMONS_DISABLE_EE=true yarn run -s test:start-app & wait-on http://localhost:3030
    - LEEMONS_DISABLE_EE=true yarn run -s test:e2e

# end to end testing template
e2e_tests_ee: &e2e_tests_ee
  stage: 'End to End tests EE'
  script:
    - yarn run -s test:generate-app -- $DB_STRING
    - yarn run -s test:start-app & wait-on http://localhost:3030
    - yarn run -s test:e2e
  if: fork = false

pg_test: &pg_test
  name: 'E2E Postgresql'
  before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - sudo apt-get update
    - sudo apt-get --yes remove postgresql-*
    - sudo apt-get install -y postgresql-11 postgresql-client-11
    - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
    - sudo service postgresql restart 11
    - psql -c 'create database leemons_test;' -U postgres
  env:
    - DB_STRING='--dbclient=postgres --dbhost=localhost --dbport=5433 --dbname=leemons_test --dbusername=postgres --dbpassword='

mongo_test: &mongo_test
  name: 'E2E MongoDB'
  before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.6.tgz
    - tar -zxvf mongodb-linux-x86_64-3.6.6.tgz
    - mkdir -p ./data/db/27017
    - mkdir -p ./data/db/27000
    - ./mongodb-linux-x86_64-3.6.6/bin/mongod --fork --dbpath ./data/db/27017 --syslog --port 27017
  env:
    - DB_STRING='--dbclient=mongo --dbhost=localhost --dbport=27017 --dbname=leemons_test'

before_script:
  - yarn build
  - yarn global add -g wait-on
  - yarn global add codecov

jobs:
  include:
    - stage: test
      name: Snyk
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      script: yarn run -s test:snyk
      if: fork = false

    - stage: test
      name: 'Lint / Unit Tests '
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      script:
        - yarn run -s lint
        - yarn run -s test:unit --coverage && codecov -C -F unit
        - yarn run -s test:front && codecov -C -F front

    - <<: *e2e_tests
      <<: *pg_test

    - <<: *e2e_tests
      <<: *mongo_test

    - <<: *e2e_tests_ee
      <<: *pg_test

    - <<: *e2e_tests_ee
      <<: *mongo_test
