version: "3.8"
services:
  leemons-yarn-install:
    image: node:16
    volumes:
      - ./src/package.json:/monorepo/package.json
      - ../examples/docker:/monorepo/app
      - ../packages:/monorepo/packages
      - ../examples/docker/monorepo_node_modules:/monorepo/node_modules
      - ../yarn.lock:/monorepo/yarn.lock
      - ./src/installDeps.sh:/monorepo/installDeps.sh
      - ./src/retry.sh:/monorepo/retry.sh
      - ./src/app/package.json:/monorepo/appPackageTemplate.json
    working_dir: /monorepo
    tty: true
    stdin_open: true
    command: sh retry.sh echo

  leemons-back:
    image: node:16
    tty: true
    stdin_open: true
    volumes:
      - ./src/package.json:/monorepo/package.json
      - ../examples/docker:/monorepo/app
      - ../packages:/monorepo/packages
      - ../examples/docker/monorepo_node_modules:/monorepo/node_modules
      - ../yarn.lock:/monorepo/yarn.lock
      - ./src/retry.sh:/monorepo/retry.sh
    links:
      - mysql
      - leemons-front
    working_dir: /monorepo/app
    command: sh ../retry.sh yarn start

  leemons-front:
    image: node:16
    tty: true
    stdin_open: true
    volumes:
      - ./src/package.json:/monorepo/package.json
      - ../packages:/monorepo/packages
      - ../examples/docker/monorepo_node_modules:/monorepo/node_modules
      - ../examples/docker:/monorepo/app
      - ../yarn.lock:/monorepo/yarn.lock
      - ./src/front/build.sh:/monorepo/build.sh
      - ./src/retry.sh:/monorepo/retry.sh
    working_dir: /monorepo
    restart: always
    depends_on:
      - leemons-yarn-install
        # condition: service_completed_successfully
    expose:
      - 3000
    ports:
      - 3000:3000
    command: sh ./retry.sh sh ./build.sh


  # leemons:
  #   image: node:16
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ./src/package.json:/monorepo/package.json
  #     - ../examples/demo-auth:/monorepo/app
  #     - ../packages:/monorepo/packages
  #     - ../node_modules:/monorepo/node_modules
  #     - ../yarn.lock:/monorepo/yarn.lock
  #     - ./src/front:/front

  #   links:
  #     - mysql
  #   working_dir: /monorepo/app
  #   command: "sh -c 'yarn global add serve; yarn --cwd .. -s; serve -p 3000 /front & yarn dev'"
  #   restart: always
  #   ports:
  #     - 8080:8080
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: leemons
      MYSQL_USER: leemons
      MYSQL_ROOT_PASSWORD: leemons
      MYSQL_PASSWORD: leemons
    expose:
      - 3306
    ports:
      - 3307:3306

  # MongoDB mono replica set
  # mongo:
