version: "3.2"
services:
  leemons:
    image: node:16-alpine
    tty: true
    stdin_open: true
    volumes:
      - ./src/package.json:/monorepo/package.json
      - ./src/.yarnrc:/monorepo/.yarnrc
      - ../examples/demo-auth:/monorepo/app
      - ../packages:/monorepo/packages
    links:
      - db:mysql
    working_dir: /monorepo
    command: "sh -c 'yarn --cwd .. -s; yarn dev'"
    ports:
      - 8080:8080
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: leemons
      MYSQL_USER: leemons
      MYSQL_ROOT_PASSWORD: leemons
      MYSQL_PASSWORD: leemons
    expose:
      - 3306
    ports:
      - 3306:3306

  # MongoDB mono replica set
  # mongo:


