name: Deploy Docker Frontend(s3,cloudfront) and Backend(ecr,ecs)

on:
  push:
    tags:
      - '*.*.*-dev'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Set env 🔧
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Print name
        run: echo "Name secret - ${{ secrets.NAME }} | Name vars - ${{ vars.NAME }}"
